### ISSUE TITLE
Dynamic Types iOS Tutorial Missing?

### ISSUE THREAD

**Issue by Mozahler** [ioscreator/ioscreator#23]
There is a folder (here on github.com/ioscreator) for the Dynamic Types iOS Tutorial described in the article here:

[Tutorial](https://www.ioscreator.com/tutorials/dynamic-types-ios-tutorial)

But it is empty. Is that intentional?

**Comment by JangWonWoong** [comment]
So sorry, This is test project..

**Comment by Mozahler** [comment]
Got it! Thx
